### ISSUE TITLE
What should be in the 0.7 release and ReadMe Updates

### ISSUE THREAD

**Issue by JordanMartinez** [TomasMikula/RichTextFX#259]
`0.6.10` was released on Oct 12. 4 months later, we've made the following changes to RichTextFX since that release:
- Skin related
  - Implemented paragraph styles (text alignment, line background color, copy & paste styles)
  - Exposed estimated scrolling API
  - Allow better access to the skin (no longer using the Control, Skin, Behavior paradigm)
  - Separated the `ScrollPane` aspect of `StyledTextArea` from the actual area itself
  - Allow access to `CharacterHit` (so can determine which character is at point x, y)
  - Implemented better caret-blinking (visible when user moves the caret, visible immediately upon showing the area)
  - Added pseudo classes for line which has the caret
  - Added pseudo classes for handling 
- Clone related
  - Allow multiple views of the same `EditableStyledDocument`
- Other
  - Converted all default `EventHandlers` to `EventHandlerTemplates`
  - Made double-clicking a word select only the word (not the leading/trailing whitespace char)
  - Removed unused and useless font property
  - Implemented `onSelectionDrop` to override default handling when moving a selection elsewhere in the area.
  - Fixed undo bug (styles from deleted text would cause a mismatch between the undone document and the one to redo)

With the numerous issues still open, what should be included in the `0.7` release and what should be postponed until `0.7.1`?

**Edit:** Include WellBehavedFX experimental code
**Edit 3/16/16:** Exclude #252 as it's no longer relevant. Added checkboxes.

Of the issues we have, I think the following should be included in the `0.7` release:
- [x] #233 because it will cause problems with cloning and overall stability.
    - This issue was closed due to being outside the scope of RTFX
- [x] Use the `WellBehavedFX` experimental InputMap API for setting default UI handlers that can be overridden (see the last few comments of #257 after it was closed) 

**Edit 9/7/16:** Removed ideas for `0.7.1` release

**Comment by JordanMartinez** [comment]
Also note that if one searches the `0.7` milestone, the only issue that arises is #210, which seems to have been fixed now.

**Comment by JordanMartinez** [comment]
I'm going to add a note here to keep track of what needs to be updated in the ReadMe when the new release is made:
- [ ] Rename deprecated `InlineStyleTextArea` to `StyledTextArea` and update related content
- [ ] Add a link to the RichtTextFX CSS Guide (optional?)

**Comment by firm1** [comment]
Hello,
Any idea about ​​the date of the release ? There are a lot of bugs fixed since I like to incorporate in my app.

**Comment by JordanMartinez** [comment]
Maybe 2-3 weeks? I'm hoping to finish resolving the last issue before that, but I don't want to give any guarantees.

**Comment by TomasMikula** [comment]
I'm fine with making a pre-release (alpha, beta, milestone, RC, whatever...). For that, I first need to make a (pre-)release of Flowless 0.5.

I still don't believe that the clones + undo issue can be solved satisfactorily by RichTextFX, so it is more important to me to give users enough control to customize the undo behavior.

**Comment by JordanMartinez** [comment]
> I still don't believe that the clones + undo issue can be solved satisfactorily by RichTextFX

That's true... Users of this library will have different use cases that prevents a one-size-fits-all solution.

**Comment by JordanMartinez** [comment]
At the same time, those who don't want to use clones won't be negatively affected by the current issue and I'm guessing that there's a larger majority that want a release with the bug fixes than those who want the undo issue fixed. 
Additionally, the same `UndoManager` interface would be used, so they can implement that themselves if they really need the non-linear undo capabilities.

**Comment by JordanMartinez** [comment]
Since RichTextFX can't satisfactorily solve the clones + undo issue, should it even be supported? If we did create a basic non-linear undo, how many developers would actually use it as opposed to designing their own?

**Comment by firm1** [comment]
for me, you can do it (basic non-linear undo). Somebody can improve this
after if you want.

Le mer. 11 mai 2016 19:42, JordanMartinez <notifications@github.com> a
écrit :

**Comment by JordanMartinez** [comment]
The ReadMe has been updated with all the items on the todo list and the remaining issue in the bugs to fix was closed due to being outside the scope of this project. Rather than make a list of other things to do before the `0.7` release is made, one should use the milestone tag in the issues to see that.
